### ISSUE TITLE
linelist identification

### ISSUE THREAD

**Issue by HajimeKawahara** [prvjapan/pyird#11]
we definitely need ecidentify like module. No more wavelength val by manual.

- [x] load Thar_ird2.dat
- [x] allocate the line positions in pixcoord 
- [x] make a prediction by some interpolation or GP? #25
-  (postpone) I would include uncertain estimate for wavelength position, probably GP is better than interpolation.

**Comment by YuiKasagi** [comment]
This is the current result.
The process of identify is as follows.

1. allocate the line positions in pixcoord
   - search a peak around the pixel listed in the channel list (e.g. channel_H.list)
   - create new channel list
2. make the 1st prediction of wavelength solution
   - fitting with Legendre function (2d): 
3. read that_ird2.dat & add reference lines
   - based on 1st wavelength solution
   - allocate the line positions by searching peaks again
4. make the 2nd prediction and iterate it until std of residual < 0.005
![wavcal_final](https://user-images.githubusercontent.com/66584422/154003569-d4a5c800-4fd7-48d7-8eee-2243dd36db50.png)
