### ISSUE TITLE
Wavelength range lost in order combining

### ISSUE THREAD

**Issue by YuiKasagi** [prvjapan/pyird#65]
When creating the 1D normalized spectrum whose overlap region with adjacent orders is combined (ncw???_m?.dat), there seem to be some minor mistakes. The problem is that a few pixels at the edge of the order are dropped because ~~they could be no signal~~ signal tends to have strange values, but the flux interpolation wavelength does not take this into account. So some wavelength ranges are lost when compared to the uncombined spectrum.
Ziying Gu found this issue. Thank you pointed this out! I will fix this.

**Comment by HajimeKawahara** [comment]
@ZiyingGu

**Comment by ZiyingGu** [comment]
Yes. It's a problem about the edge of the overlap region of two orders.
I draw a figure and attach some example data.
[Figure.pdf](https://github.com/prvjapan/pyird/files/10564205/Figure.pdf)
[Range A of the overlap region.pdf](https://github.com/prvjapan/pyird/files/10564206/Range.A.of.the.overlap.region.pdf)
[Range B of the overlap region.pdf](https://github.com/prvjapan/pyird/files/10564207/Range.B.of.the.overlap.region.pdf)

**Comment by YuiKasagi** [comment]
This is an image of what I (we) want to do...
![concept_of_combine_flux](https://user-images.githubusercontent.com/66584422/216251368-7ac95869-6e2e-47f4-b73e-cd491473771b.jpg)

**Comment by ZiyingGu** [comment]
So values of the left side of overlap region (no signal + 2 pix) should be calculated as (flux of former order)/(blaze function of the former order), behaving the same as the data points beyond the overlap region of the former order, right? Similar to the right side.

**Comment by YuiKasagi** [comment]
@ZiyingGu Yes, that's right. I intended that outside the overlap region should match the original (former or latter order's) flux values and wavelength gird, and the calculation for normalization.
