### ISSUE TITLE
hot pixel mask

### ISSUE THREAD

**Issue by HajimeKawahara** [prvjapan/pyird#8]
Using sep, I constructed the hotpixel identification, though not well-tested.

**Comment by HajimeKawahara** [comment]
Anyway done.

**Comment by YuiKasagi** [comment]
When I tried to identify sky emissions, I found that there remain (many) hot pixels even after masking them.
These figures show a raw detector image of a dark frame and a hot pixel mask made from it by current pyird.
(They are zoomed up where the hot pixel cluster exists to make it easy to see. This cluster doesn't affect the extracted spectrum, though.)
You can see that the cross-shaped hot pixel cannot identify correctly.

I will revise the code to identify hot pixels (or make a new one). 
<img width="890" alt="スクリーンショット 2022-09-07 15 52 38" src="https://user-images.githubusercontent.com/66584422/188820061-68ac6a23-bed4-4adb-9441-c404c2de2aca.png">

**Comment by HajimeKawahara** [comment]
Yeah, the last one I made was a very beta version. I agree that we need to revise it!

**Comment by YuiKasagi** [comment]
The hotpixel mask is updated in #58
